In [2]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import GridSearchCV

In [6]:
cc_apps=pd.read_csv('cc_approval.csv')

In [7]:
cc_apps.head()

   b  30.83      0  u  g  w  v  1.25  t t.1  01  f g.1  00202  0.1  +
0  a  58.67  4.460  u  g  q  h  3.04  t   t   6  f   g  00043  560  +
1  a  24.50  0.500  u  g  q  h  1.50  t   f   0  f   g  00280  824  +
2  b  27.83  1.540  u  g  w  v  3.75  t   t   5  t   g  00100    3  +
3  b  20.17  5.625  u  g  w  v  1.71  t   f   0  f   s  00120    0  +
4  b  32.08  4.000  u  g  m  v  2.50  t   f   0  t   g  00360    0  +

In [8]:
# Print summary statistics
cc_apps_description = cc_apps.describe()
print(cc_apps_description)

print("\n")

# Print DataFrame information
cc_apps_info = cc_apps.info()
print(cc_apps_info)

print("\n")

# Inspect missing values in the dataset

cc_apps.tail(17)

                0        1.25          01            0.1
count  689.000000  689.000000  689.000000     689.000000
mean     4.765631    2.224819    2.402032    1018.862119
std      4.978470    3.348739    4.866180    5213.743149
min      0.000000    0.000000    0.000000       0.000000
25%      1.000000    0.165000    0.000000       0.000000
50%      2.750000    1.000000    0.000000       5.000000
75%      7.250000    2.625000    3.000000     396.000000
max     28.000000   28.500000   67.000000  100000.000000


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 689 entries, 0 to 688
Data columns (total 16 columns):
b        689 non-null object
30.83    689 non-null object
0        689 non-null float64
u        689 non-null object
g        689 non-null object
w        689 non-null object
v        689 non-null object
1.25     689 non-null float64
t        689 non-null object
t.1      689 non-null object
01       689 non-null int64
f        689 non-null object
g.1      689 non-null object
00202    689 non-null object
0.1      689 non-null int64
+        689 non-null object
dtypes: float64(2), int64(2), object(12)
memory usage: 86.2+ KB
None

     b  30.83       0  u  g   w   v   1.25  t t.1  01  f g.1  00202  0.1  +
672  ?  29.50   2.000  y  p   e   h  2.000  f   f   0  f   g  00256   17  -
673  a  37.33   2.500  u  g   i   h  0.210  f   f   0  f   g  00260  246  -
674  a  41.58   1.040  u  g  aa   v  0.665  f   f   0  f   g  00240  237  -
675  a  30.58  10.665  u  g   q   h  0.085  f   t  12  t   g  00129    3  -
676  b  19.42   7.250  u  g   m   v  0.040  f   t   1  f   g  00100    1  -
677  a  17.92  10.210  u  g  ff  ff  0.000  f   f   0  f   g  00000   50  -
678  a  20.08   1.250  u  g   c   v  0.000  f   f   0  f   g  00000    0  -
679  b  19.50   0.290  u  g   k   v  0.290  f   f   0  f   g  00280  364  -
680  b  27.83   1.000  y  p   d   h  3.000  f   f   0  f   g  00176  537  -
681  b  17.08   3.290  u  g   i   v  0.335  f   f   0  t   g  00140    2  -
682  b  36.42   0.750  y  p   d   v  0.585  f   f   0  f   g  00240    3  -
683  b  40.58   3.290  u  g   m   v  3.500  f   f   0  t   s  00400    0  -
684  b  21.08  10.085  y  p   e   h  1.250  f   f   0  f   g  00260    0  -
685  a  22.67   0.750  u  g   c   v  2.000  f   t   2  t   g  00200  394  -
686  a  25.25  13.500  y  p  ff  ff  2.000  f   t   1  t   g  00200    1  -
687  b  17.92   0.205  u  g  aa   v  0.040  f   f   0  f   g  00280  750  -
688  b  35.00   3.375  u  g   c   h  8.290  f   f   0  t   g  00000    0  -

In [9]:
# Inspect missing values in the dataset
# Replace the '?'s with NaN
cc_apps = cc_apps.replace(['?'],np.NaN)
# Inspect the missing values again
cc_apps.tail(17)

       b  30.83       0  u  g   w   v   1.25  t t.1  01  f g.1  00202  0.1  +
672  NaN  29.50   2.000  y  p   e   h  2.000  f   f   0  f   g  00256   17  -
673    a  37.33   2.500  u  g   i   h  0.210  f   f   0  f   g  00260  246  -
674    a  41.58   1.040  u  g  aa   v  0.665  f   f   0  f   g  00240  237  -
675    a  30.58  10.665  u  g   q   h  0.085  f   t  12  t   g  00129    3  -
676    b  19.42   7.250  u  g   m   v  0.040  f   t   1  f   g  00100    1  -
677    a  17.92  10.210  u  g  ff  ff  0.000  f   f   0  f   g  00000   50  -
678    a  20.08   1.250  u  g   c   v  0.000  f   f   0  f   g  00000    0  -
679    b  19.50   0.290  u  g   k   v  0.290  f   f   0  f   g  00280  364  -
680    b  27.83   1.000  y  p   d   h  3.000  f   f   0  f   g  00176  537  -
681    b  17.08   3.290  u  g   i   v  0.335  f   f   0  t   g  00140    2  -
682    b  36.42   0.750  y  p   d   v  0.585  f   f   0  f   g  00240    3  -
683    b  40.58   3.290  u  g   m   v  3.500  f   f   0  t   s  00400    0  -
684    b  21.08  10.085  y  p   e   h  1.250  f   f   0  f   g  00260    0  -
685    a  22.67   0.750  u  g   c   v  2.000  f   t   2  t   g  00200  394  -
686    a  25.25  13.500  y  p  ff  ff  2.000  f   t   1  t   g  00200    1  -
687    b  17.92   0.205  u  g  aa   v  0.040  f   f   0  f   g  00280  750  -
688    b  35.00   3.375  u  g   c   h  8.290  f   f   0  t   g  00000    0  -

In [10]:
# Impute the missing values with mean imputation
cc_apps.fillna(cc_apps.mean(), inplace=True)

# Count the number of NaNs in the dataset to verify
pd.isna(cc_apps)
cc_apps.tail(17)

       b  30.83       0  u  g   w   v   1.25  t t.1  01  f g.1  00202  0.1  +
672  NaN  29.50   2.000  y  p   e   h  2.000  f   f   0  f   g  00256   17  -
673    a  37.33   2.500  u  g   i   h  0.210  f   f   0  f   g  00260  246  -
674    a  41.58   1.040  u  g  aa   v  0.665  f   f   0  f   g  00240  237  -
675    a  30.58  10.665  u  g   q   h  0.085  f   t  12  t   g  00129    3  -
676    b  19.42   7.250  u  g   m   v  0.040  f   t   1  f   g  00100    1  -
677    a  17.92  10.210  u  g  ff  ff  0.000  f   f   0  f   g  00000   50  -
678    a  20.08   1.250  u  g   c   v  0.000  f   f   0  f   g  00000    0  -
679    b  19.50   0.290  u  g   k   v  0.290  f   f   0  f   g  00280  364  -
680    b  27.83   1.000  y  p   d   h  3.000  f   f   0  f   g  00176  537  -
681    b  17.08   3.290  u  g   i   v  0.335  f   f   0  t   g  00140    2  -
682    b  36.42   0.750  y  p   d   v  0.585  f   f   0  f   g  00240    3  -
683    b  40.58   3.290  u  g   m   v  3.500  f   f   0  t   s  00400    0  -
684    b  21.08  10.085  y  p   e   h  1.250  f   f   0  f   g  00260    0  -
685    a  22.67   0.750  u  g   c   v  2.000  f   t   2  t   g  00200  394  -
686    a  25.25  13.500  y  p  ff  ff  2.000  f   t   1  t   g  00200    1  -
687    b  17.92   0.205  u  g  aa   v  0.040  f   f   0  f   g  00280  750  -
688    b  35.00   3.375  u  g   c   h  8.290  f   f   0  t   g  00000    0  -

In [13]:
# Iterate over each column of cc_apps
cc_apps=cc_apps.fillna(method='ffill')
# Count the number of NaNs in the dataset and print the counts to verify
# ... YOUR CODE FOR TASK 5 ...
print(cc_apps.count())
cc_apps.tail(20)

b        689
30.83    689
0        689
u        689
g        689
w        689
v        689
1.25     689
t        689
t.1      689
01       689
f        689
g.1      689
00202    689
0.1      689
+        689
dtype: int64

     b  30.83       0  u  g   w   v   1.25  t t.1  01  f g.1  00202  0.1  +
669  b  47.17   5.835  u  g   w   v  5.500  f   f   0  f   g  00465  150  -
670  b  25.83  12.835  u  g  cc   v  0.500  f   f   0  f   g  00000    2  -
671  a  50.25   0.835  u  g  aa   v  0.500  f   f   0  t   g  00240  117  -
672  a  29.50   2.000  y  p   e   h  2.000  f   f   0  f   g  00256   17  -
673  a  37.33   2.500  u  g   i   h  0.210  f   f   0  f   g  00260  246  -
674  a  41.58   1.040  u  g  aa   v  0.665  f   f   0  f   g  00240  237  -
675  a  30.58  10.665  u  g   q   h  0.085  f   t  12  t   g  00129    3  -
676  b  19.42   7.250  u  g   m   v  0.040  f   t   1  f   g  00100    1  -
677  a  17.92  10.210  u  g  ff  ff  0.000  f   f   0  f   g  00000   50  -
678  a  20.08   1.250  u  g   c   v  0.000  f   f   0  f   g  00000    0  -
679  b  19.50   0.290  u  g   k   v  0.290  f   f   0  f   g  00280  364  -
680  b  27.83   1.000  y  p   d   h  3.000  f   f   0  f   g  00176  537  -
681  b  17.08   3.290  u  g   i   v  0.335  f   f   0  t   g  00140    2  -
682  b  36.42   0.750  y  p   d   v  0.585  f   f   0  f   g  00240    3  -
683  b  40.58   3.290  u  g   m   v  3.500  f   f   0  t   s  00400    0  -
684  b  21.08  10.085  y  p   e   h  1.250  f   f   0  f   g  00260    0  -
685  a  22.67   0.750  u  g   c   v  2.000  f   t   2  t   g  00200  394  -
686  a  25.25  13.500  y  p  ff  ff  2.000  f   t   1  t   g  00200    1  -
687  b  17.92   0.205  u  g  aa   v  0.040  f   f   0  f   g  00280  750  -
688  b  35.00   3.375  u  g   c   h  8.290  f   f   0  t   g  00000    0  -

In [14]:
le=LabelEncoder()
# Iterate over all the values of each column and extract their dtypes
for col in cc_apps:
    # Compare if the dtype is object
    if cc_apps[col].dtype=='object':
    # Use LabelEncoder to do the numeric transformation
         cc_apps[col]=le.fit_transform(cc_apps[col])
cc_apps.head()

   b  30.83      0  u  g   w  v  1.25  t  t.1  01  f  g.1  00202  0.1  +
0  0    327  4.460  1  0  10  3  3.04  1    1   6  0    0     11  560  0
1  0     89  0.500  1  0  10  3  1.50  1    0   0  0    0     95  824  0
2  1    125  1.540  1  0  12  7  3.75  1    1   5  1    0     31    3  0
3  1     43  5.625  1  0  12  7  1.71  1    0   0  0    2     37    0  0
4  1    167  4.000  1  0   9  7  2.50  1    0   0  1    0    114    0  0

In [15]:
# Drop features 10 and 13 and convert the DataFrame to a NumPy array
cc_apps = cc_apps.drop(columns=['01', '00202'], axis=1)
cc_apps = cc_apps.values

# Segregate features and labels into separate variables
rescaledX,y = cc_apps[:,0:13] , cc_apps[:,13]
#X.tolist()
# Instantiate MinMaxScaler and use it to rescale
#scaler = MinMaxScaler(copy=True,feature_range=(0,1))
#rescaledX=scaler.fit(X)

In [16]:
# Split into train and test sets
X_train, X_test, y_train, y_test = train_test_split(rescaledX,y,test_size=0.33,random_state=42)

In [17]:
# Instantiate a LogisticRegression classifier with default parameter values
logreg = LogisticRegression()

# Fit logreg to the train set
logreg.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [22]:
y_pred = logreg.predict(X_test)

# Get the accuracy score of logreg model and print it
print("Accuracy of logistic regression classifier: ",logreg.score(X_test,y_test))

# Print the confusion matrix of the logreg model

print(confusion_matrix(y_test,y_pred))

Accuracy of logistic regression classifier:  0.868421052631579
[[ 95   5]
 [ 25 103]]

In [23]:
# Define the grid of values for tol and max_iter
tol = [0.01,0.001,0.0001]
max_iter = [100,150,200]

# Create a dictionary where tol and max_iter are keys and the lists of their values are corresponding values
param_grid = dict(tol=tol, max_iter=max_iter)

In [24]:
# Instantiate GridSearchCV with the required parameters
grid_model = GridSearchCV(estimator=logreg, param_grid=param_grid, cv=5)

# Fit data to grid_model
grid_model_result = grid_model.fit(rescaledX, y)

# Summarize results
best_score, best_params = grid_model_result.best_score_,grid_model_result.best_params_
print("Best: %f using %s" % (best_score, best_params))

Best: 0.843251 using {'max_iter': 100, 'tol': 0.0001}